services:
  logstash:
    image: docker.elastic.co/logstash/logstash:8.13.0
    container_name: logstash
    ports:
      - "5000:5000" # Puerto que escuchará Logstash
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    environment:
      - "LS_JAVA_OPTS=-Xmx512m -Xms512m"
    networks:
      - ms-network

networks:
  ms-network:
    external: true
