services:
  logstash:
    image: docker.elastic.co/logstash/logstash:8.13.0
    container_name: logstash
    ports:
      - "5000:5000" # Puerto que escuchará Logstash
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    environment:
      - "LS_JAVA_OPTS=-Xmx512m -Xms512m"
    networks:
      - ms-network
  
  grafana:
    image: grafana/grafana:10.0.0
    container_name: grafana
    ports:
      - "8989:3000"  # Acceso a Grafana desde localhost:8989
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - ms-network

volumes:
  grafana-storage:

networks:
  ms-network:
    external: true
